# Generated by Django 5.2.12 on 2026-03-09 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('face_capture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='detections/')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_detections', to='face_capture.person')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
