# Generated by Django 5.2.12 on 2026-03-09 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
        ('face_capture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonedetection',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_detections', to='face_capture.person'),
        ),
    ]
