# Generated by Django 5.2.11 on 2026-04-07 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_alter_phonedetection_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestrictedArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='phonedetection',
            options={'ordering': ['-detection_time']},
        ),
        migrations.RenameField(
            model_name='phonedetection',
            old_name='detected_at',
            new_name='detection_time',
        ),
        migrations.AddField(
            model_name='phonedetection',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phonedetection',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='detection.restrictedarea'),
        ),
    ]
